### ISSUE TITLE
Allow providing a custom css file when using docker

### ISSUE THREAD

**Issue by owenfiscus** [sigoden/duf#12]

**Comment by sigoden** [comment]
Do you want to customize the styles of default page or serve your own html/css file?

**Comment by owenfiscus** [comment]
For my use case personally, either option would work. I'm simply looking to modify the style of the default page.

Great work on this project by the way!

**Comment by sigoden** [comment]
1. put your index.html to /data
2. run with `duf /data --render-index`
3. for signle-page application, run with `duf /data --render-spa`

**Comment by sigoden** [comment]
The easiest way is folk and customize. Duf is a **simple** file server. This features will add some complexity and is not very necessary.
