### ISSUE TITLE
bug: filenames aren't properly escaped in WebDAV PROPFIND

### ISSUE THREAD

**Issue by jkoop** [sigoden/duf#19]
To reproduce the issue, create a folder with a file called `This & that`. Try to mount the folder via WebDAV. See it fail (possibly with an XML parse error).

Excerpts from the PROPFIND response from `duf` and `apache2`:

```xml
<!-- duf -->
<D:href>/path/to/This & that</D:href>
<D:displayname>This & that</D:displayname>
```

```xml
<!-- apache2 -->
<D:href>/path/to/This%20&amp;%20that</D:href>
```

**Comment by jkoop** [comment]
Fixed by PR 20

**Comment by jkoop** [comment]
@sigoden's fix didn't fix this issue.

**Comment by sigoden** [comment]
![image](https://user-images.githubusercontent.com/4012553/172075118-05faab69-5a5d-44a2-a6fa-e91b0cc9ead3.png)

I have  tested it on windows dav. It works. @jkoop
