### ISSUE TITLE
[Suggestion] Web static directory support

### ISSUE THREAD

**Issue by 834772509** [sigoden/duf#37]
I tried to write a web page suitable for "duf" by myself. The main layout was referenced from [h5ai](https://larsjung.de/h5ai/), and it was packaged with Webpack, but the packaged pictures were scattered. Can Web Static Directory Support be Added? When the browser requests any file, it requests the files in the "assets" directory.

**Comment by sigoden** [comment]
duf can serve static files. 

I do not quite understand what you mean。

If  your assets contains `img1.png`

run `duf assets`, access it with `http://localhost:5000/img1.png`
run `duf assets --path-prefix assets`, access it with `http://localhost:5000/assets/img1.png`

**Comment by 834772509** [comment]
For example, store "duf-src\assets\img1.png" in the "assets" directory of the "duf" source code, then you can access http://localhost:5000/img1.png

**Comment by 834772509** [comment]
Oh, I got it, I just need to convert all the images to base64 and package them in the index.html file, disturb you.
