### ISSUE TITLE
Cannot handle shortcuts in windows very well

### ISSUE THREAD

**Issue by piaoger** [sigoden/duf#4]
Just tried shortcuts in Windows and I suppose it cannot deal with symbol link very well in Linux or Mac.

Error Message: Internal Server Error
ENV: Firefox Windows

![image](https://user-images.githubusercontent.com/179429/171145455-1bda3006-946e-41d1-8dae-658037000a17.png)

**Comment by piaoger** [comment]
> No problem in win10, what is your windows version?
win11 but I will setup up static server in Linux
 finally.

**Comment by sigoden** [comment]
@piaoger I tested it in wsl2, but didn't find the problem you mentioned. Could you post the error log?

**Comment by piaoger** [comment]
> @piaoger I tested it in wsl2, but didn't find the problem you mentioned. Could you post the error log?

I just downloaded and tried your released version for windows, not in WSL2 instead.
Pakcage Name: duf-v0.6.0-x86_64-pc-windows-msvc.zip
log:   [duf::server] "GET /My%20Documents" - 500 Internal Server Error 拒绝访问。 (os error 5)

However, I found the latest duf-v0.7.0-x86_64-pc-windows-msvc.zip is blocked by bitdefender :)

![1654071491(1)](https://user-images.githubusercontent.com/179429/171360090-26890030-5fc7-4e76-9161-be37d87e30f1.png)

**Comment by sigoden** [comment]
I have submitted the file to [Microsoft Security Intelligence](https://www.microsoft.com/en-us/wdsi/filesubmission) for malware analysis.

Now microsoft defender will not incorrectly detected it as malware/malicious.
