### ISSUE TITLE
[Feature Request] enhance --render-index functionality

### ISSUE THREAD

**Issue by shiggins8** [sigoden/duf#46]
First of all, this is a very cool tool, so thank you for the development efforts. The addition of the --render-index argument is great. This might not be a common use case, but I've got a file server that is probably 50/50 split, where half of the directories contain an index.html and half do not. Currently, when I set that flag, any directory that doesn't have an index.html file just renders a blank page (404 from the server, since the file wasn't found). 

Is there any way to make that argument kick in when there is a index.html file present, but fall back to the default rendering of a directory if not? Would be a very nice enhancement.

**Comment by sigoden** [comment]
Add `--render-try-index` for this situration

**Comment by shiggins8** [comment]
@sigoden extremely fast response time, many thanks!
