### ISSUE TITLE
[Feature request] File encryption

### ISSUE THREAD

**Issue by nicolaspernoud** [sigoden/duf#49]
Hello,
Thanks for this amazing work.
It would be nice to have an option to encrypt files in place providing a key as argument.
That should be probably achievable with something like described here : https://kerkour.com/rust-file-encryption, apart from the tricky part of working out the real file size from the encrypted file size... and to store a generated per file nonce as an encrypted file header, so that the nonce is not the same for each file, but recoverable from the file itself...
Best regards.

**Comment by sigoden** [comment]
Thanks for your suggestion.

File encryption is too niche and too professional for a simple file server.

Object storage like s3/minio  is good at this.

**Comment by nicolaspernoud** [comment]
Ok, I understand. Thanks for your answer.
