### ISSUE TITLE
Rename duf to dufs

### ISSUE THREAD

**Issue by KSXGitHub** [sigoden/duf#50]
There's another tool also called [duf](https://github.com/muesli/duf) whose command is also `duf`.

Various Linux distributions (Arch Linux, Debian, Nix, etc) already provide a package named `duf` that provides the other `duf`.

**Proposal:** Rename this tool to allow users to use it without name/file conflict.

**Comment by jkoop** [comment]
Do you have any alternative names in mind?

**Comment by jkoop** [comment]
What about `duuf`?

(I hope this isn't offensive; I didn't do any research)

**Comment by sigoden** [comment]
Maybe `dufs`.

**Comment by jkoop** [comment]
I like that

**Comment by KSXGitHub** [comment]
`dufs` is cool.

BTW, what does `duf` stand for?

**Comment by sigoden** [comment]
download/upload file server

**Comment by KSXGitHub** [comment]
> download/upload file server

Then `dufs` is perfect.

**Comment by KSXGitHub** [comment]
@sigoden I think you should rename the GitHub repo as well (from `sigoden/duf` to `sigoden/dufs`). Also check if there's any broken links or references in the docs.

**Comment by sigoden** [comment]
I will do it after ci finished
