### ISSUE TITLE
什么指令可以查看访问日志？

### ISSUE THREAD

**Issue by zy1818** [sigoden/duf#55]
请问 什么指令可以查看访问日志？  谢谢

**Comment by sigoden** [comment]
运行时就会打印访问日志

**Comment by zy1818** [comment]
看到了  谢谢

**Comment by zy1818** [comment]
可以单文件共享吗&nbsp; 没看明白


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sigoden/duf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月19日(星期天) 中午12:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sigoden/duf] 什么指令可以查看访问日志？ (Issue #55)





 
运行时就会打印访问日志

**Comment by sigoden** [comment]
等 pr 合并，并发布新版本之后才行

**Comment by zy1818** [comment]
还有个问题，qq浏览器访问看不到任何文件&nbsp; &nbsp; 其它浏览器没问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sigoden/duf"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月19日(星期天) 中午1:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sigoden/duf] 什么指令可以查看访问日志？ (Issue #55)





 
等 pr 合并，并发布新版本之后才行

**Comment by zy1818** [comment]
期待中，你哪个地区的，你这个不错。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月19日(周日) 中午1:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sigoden/duf] 什么指令可以查看访问日志？ (Issue #55)




 
等 pr 合并，并发布新版本之后才行
