### ISSUE TITLE
希望可以增加设置title的功能

### ISSUE THREAD

**Issue by vip123456789** [sigoden/duf#56]
你好，希望可以增加设置title的功能，现在默认的title好像是文件夹的名称

**Comment by sigoden** [comment]
有这个必要吗？可以问下你准备设置成什么吗？

**Comment by vip123456789** [comment]
比如说index，或者.来标识当前目录

**Comment by sigoden** [comment]
```
duf data
```
根目录是 `data`，各级目录形成的 title 是

`data/ - Duf` 
`data/dira/ - Duf`
`data/dira/dirb/ - Duf`
```
这不合理吗？

**Comment by vip123456789** [comment]
比如说只是不想显示根目录名称呢
/ - Duf
/dira/ - Duf
/dira/dirb/ - Duf

或者是
Index of/ - Duf
Index of/dira/ - Duf
Index of/dira/dirb/ - Duf
或者是
./ - Duf
./dira/ - Duf
./dira/dirb/ -Duf

**Comment by sigoden** [comment]
可以调整成这种 `Index of /dira/dirb/ - Duf`
